### ISSUE TITLE
Latest big5-to-utf8 still cause error

### ISSUE THREAD

**Issue by ac9607** [godfat/cultivate#6]
With latest version of big5-to-utf8 will cause invalid byte sequence in UTF-8 (ArgumentError)
It's fine with older version

wangyps-MacBook-Pro-2:cultivate wangyp$ ./bin/import /Users/wangyp/Documents/cultivate/data20180907
Traceback (most recent call last):
	9: from ./bin/import:7:in `<main>'
	8: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `traverse'
	7: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `each'
	6: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `block in traverse'
	5: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `each'
	4: from ./bin/import:8:in `block in <main>'
	3: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:20:in `import'
	2: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:40:in `load_rows'
	1: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:50:in `load_csv'
/Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:50:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by godfat** [comment]
It's giving this errors for some files, or all of them? If it's just some files, send me a sample privately?

**Comment by ac9607** [comment]
All of them

**Comment by godfat** [comment]
@ac9607 It works for me though?

```
21:21 ~/p/g/cultivate master> ruby bin/big5-to-utf8 data/
21:21 ~/p/g/cultivate master>
```

**Comment by godfat** [comment]
Still having issue?

**Comment by ac9607** [comment]
The error does not occur constantly, so I may need the log to find out what was happened. 
By the way, In recent try, I encoded files with mixture of UTF-8 encoded and non-UTF-8 encoded files smoothly without any error occurred, but the error occurred at importing.

wangyps-MacBook-Pro-2:cultivate wangyp$ ./bin/big5-to-utf8_new /Users/wangyp/Documents/cultivate/dataall
wangyps-MacBook-Pro-2:cultivate wangyp$ ./bin/import /Users/wangyp/Documents/cultivate/dataall
	9: from ./bin/import:7:in `<main>'
	8: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `traverse'
	7: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `each'
	6: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `block in traverse'
	5: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `each'
	4: from ./bin/import:8:in `block in <main>'
	3: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:20:in `import'
	2: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:40:in `load_rows'
	1: from /Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:50:in `load_csv'
/Users/wangyp/Documents/cultivate/lib/cultivate/model.rb:50:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by godfat** [comment]
Oh, yes, I didn't realize you're talking about importing. So it looks like the problem is that `big5-to-utf8` doesn't properly transcode all data into UTF-8.

Could you make sure `big5-to-utf8_new` is update-to-date with the current `bin/big5-to-utf8`?

**Comment by godfat** [comment]
Bah, wait, I think `bin/big5-to-utf8` just isn't expected to work that way. I forgot that:

``` ruby
content = File.read(path, :encoding => 'big5-uao')
```

This simply assumes that all the files are encoded in Big5-UAO, which is not the case here. We might need to guess the encoding if we're mixing data...

**Comment by godfat** [comment]
Umm... but this still can't explain it completely because we're not writing to the files if they're not valid UTF-8.

I think I still need the data to check what's up. Please find it and send me somehow so I could better diagnose this.
